### PR TITLE
Some minor cosmetic changes

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by Natim** [comment]
I like the namespace stuff, also I find the scenario much less lisible flatten like this.

**Comment by leplatrem** [comment]
I'm glad you like it, it took me some time huhu :D

**Comment by leplatrem** [comment]
Oh, "much less lisible", my brain read the contrary :)

**Comment by almet** [comment]
Great, thanks for making this more usable ;)

**Pull request merged**
