### PR TITLE
Import Kept code !

### PR DESCRIPTION
**Pull request by leplatrem**
If Kept ought to be our reference app, its integration with Daybed should be smooth, consistent and dead simple!

We can't pretend to be sexy and expect developpers to write complex code like in https://github.com/n1k0/kept/pull/26

That's why I took the code from Kept daybed storage and propose to include it in daybed.js. If we needed this for Kept, others will for their app.

Only thing I decided to leave in Kept (and we might discuss it), is the concatenation of records from different models into a single list...

Daybed storage in Kept becomes : 

``` javascript
DaybedStore.prototype = {
  setUp: function() {
    var self = this;
    return Daybed.startSession(self._options.host, {
      token: self._options.token
    })
    .then(function(session) {
      self._session = session;
      self._session.prefix = PREFIX + session.token.slice(0, 5);
      self._options.onSession(session);

      return self._session.addModels(self._types);
    });
  },

  load: function() {
    return this._session.getRecords(this._types.keys())
      .then(function (allRecords) {
        var data = [];
        for(var model in allRecords) {
          var records = allRecords[model];
          records.forEach(function (record) {
            record.type = model;
            data.push(record);
          })
        }
        return data;
      });
  },

  save: function(data) {
    var byModelId = {};
    data.forEach(function (record) {
      if (byModelId[record.type] === undefined)
        byModelId[record.type] = [];
      byModelId[record.type].push(record);
    });
    return this._session.synchronizeRecords(byModelId);
  }
};
```
- [x] Import code
- [x] Object equals util
- [x] Unit tests
- [ ] Decide if we import the pattern of storing `type` attribute in records to distinguish them (will make Kept integration a lot shorter)

### CODE REVIEW

**Comment by leplatrem** [comment]
Ready to review/merge :)

And let's discuss the last task !

**Comment by almet** [comment]
Can't we have the type defined by kept directly? (and a requirement for the objects)

**Comment by leplatrem** [comment]
It's already the case...  Kept sets the type on all objects.

Instead of moving this part to daybed.js, I would define two new functions in Kept utils so that DaybedStore becomes very light and clear ...

(_draft_) 

``` js
function flatten(allRecords) {
        var data = [];
        for(var model in allRecords) {
          var records = allRecords[model];
          records.forEach(function (record) {
            record.type = model;
            data.push(record);
          })
        }
        return data;
}

function groupBy(data) {
        var byModelId = {};
    data.forEach(function (record) {
      if (byModelId[record.type] === undefined)
        byModelId[record.type] = [];
      byModelId[record.type].push(record);
    });
return byModelId;
}


```

By the way, can you explain the pattern you chose to prefix with credentials id ?

**Comment by leplatrem** [comment]
Bump !

**Comment by Natim** [comment]
LGTM

**Pull request merged**
