### PR TITLE
Add examples folder

### PR DESCRIPTION
**Pull request by leplatrem**
Rebased on pr #18 

The React example works well :) And illustrates the minimal code required for daybed.js integration
- [x] **React** : TODO
- [x] **jQuery**: fullcalendar
- [x] **Leaflet**: meteor-leaflet demo clone
- [x] **Angular**: wishlist app
- [x] **[wingspan](https://github.com/wingspan/wingspan-forms)** : Form validation and errors
- [ ] ~~Ember~~ gave up
- [ ] ~~Offline first~~ daybed.js not ready

Ideas : 
- Wiki (client-side markdown rendering, each page is a record, everyone read_all )
- ~~Wishlist (each wishlist is one record with field type list of objects)~~ c.f Angular
- Comments system (à la disqus)
- Quotes
- Draw on a wall (à la http://leplatrem.github.io/Leaflet.gribouille/)

Notes :
- Fluxxor http://fluxxor.com/guides/quick-start.html
- http://semu.github.io/timesheet.js/
- http://timeline.knightlab.com/
- http://remarkjs.com

### CODE REVIEW

**Comment by Natim** [comment]
I love the fullcalendar example, also when resizing an event a new one is created instead of modifying the previous one.

**Comment by almet** [comment]
Wow, wingspan is great! It seems to be a good start for daybed forms. (react ftw)

**Comment by leplatrem** [comment]
@Natim @ametaireau Yesterday night, I created a wishlist app with Angular :)

IMHO You can review/merge this PR. I keep the listed ideas for later...

**Comment by leplatrem** [comment]
Note that all examples use 'https://daybed.lolnet.org', whose SSL certificate is not trustable.

Should we migrate them to 'https://api.daybed.io'  ?

**Comment by almet** [comment]
that's pretty cool. We probably should use daybed.io everywhere rather than using the lolnet instance, I believe.

Otherwise, that's a pretty cool list of apps :)

**Comment by Natim** [comment]
For know daybed.io doesn't handle Unicode nor Elasticsearch indexes, I am working on the Unicode fix but I think it is best if we keep both lolnet and daybed.io for know.

**Pull request merged**
