### PR TITLE
Add GetOrCreateToken that make a promise and let you get stored credentials or new ones.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by leplatrem** [comment]
Why wouldn't you always use the same method ?
In other words, why would you like to keep both versions (get and getorcreate) ? 

I think we could merge both of them into a single one and add an option to force creation

**Comment by Natim** [comment]
That's an interesting question. My answer is in your response. I want a function to create new tokens and another one to get me that tokens unless they expired.

**Comment by leplatrem** [comment]
I find `getOrCreateToken` quite ugly to be honest :)

Which one would you use most ?

I would suggest `getToken()`, that returns existing token or create if expired/missing. And `getToken({ create: false })` that return the token and never create. Or the other way around depending which situation is the most frequently used...

**Comment by almet** [comment]
I like with @leplatrem's proposal: passing the parameters to getToken avoids introducing a new function name and seems quite straightforward to me.

**Comment by leplatrem** [comment]
Splitted in #7 and #8, can now close this :)

**Pull request closed without merging**
